# author: d4ryus - https://github.com/d4ryus/
# file: Makefile
# vim:set noexpandtab:ft=sh:

CC=javac

all: Server Client

Server: Server.java
	${CC} Server.java

Client: Client.java
	${CC} Client.java
